// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApplication1.Context;

#nullable disable

namespace WebApplication1.Models
{
    [DbContext(typeof(MyDbContext))]
    partial class MyDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebApplication1.Migrations.App", b =>
                {
                    b.Property<int>("AppID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AppID"));

                    b.Property<string>("AppName")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.HasKey("AppID")
                        .HasName("PK__App__8E2CF7D90C92F622");

                    b.ToTable("App", (string)null);
                });

            modelBuilder.Entity("WebApplication1.Migrations.App_Baza", b =>
                {
                    b.Property<int?>("IDApp")
                        .HasColumnType("int");

                    b.Property<int?>("IDBaza")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasIndex("IDApp");

                    b.HasIndex("IDBaza");

                    b.ToTable("App_Baza", (string)null);
                });

            modelBuilder.Entity("WebApplication1.Migrations.App_Baza_Okolina", b =>
                {
                    b.Property<int?>("IDApp")
                        .HasColumnType("int");

                    b.Property<int?>("IDBaza")
                        .HasColumnType("int");

                    b.Property<int?>("IDOKL")
                        .HasColumnType("int");

                    b.Property<string>("Link")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasIndex("IDApp");

                    b.HasIndex("IDBaza");

                    b.HasIndex("IDOKL");

                    b.ToTable("App_Baza_Okolina", (string)null);
                });

            modelBuilder.Entity("WebApplication1.Migrations.Baza", b =>
                {
                    b.Property<int>("BazaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BazaID"));

                    b.Property<string>("BazaName")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.HasKey("BazaID")
                        .HasName("PK__Baza__BEC41B4FECB7A9DD");

                    b.ToTable("Baza", (string)null);
                });

            modelBuilder.Entity("WebApplication1.Migrations.Okolina", b =>
                {
                    b.Property<int>("OKLID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OKLID"));

                    b.Property<string>("OKLName")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.HasKey("OKLID")
                        .HasName("PK__Okolina__76145ED8FCC647A2");

                    b.ToTable("Okolina", (string)null);
                });

            modelBuilder.Entity("WebApplication1.Migrations.App_Baza", b =>
                {
                    b.HasOne("WebApplication1.Migrations.App", "IDAppNavigation")
                        .WithMany()
                        .HasForeignKey("IDApp")
                        .HasConstraintName("FK__App_Baza__IDApp__4E88ABD4");

                    b.HasOne("WebApplication1.Migrations.Baza", "IDBazaNavigation")
                        .WithMany()
                        .HasForeignKey("IDBaza")
                        .HasConstraintName("FK__App_Baza__IDBaza__4F7CD00D");

                    b.Navigation("IDAppNavigation");

                    b.Navigation("IDBazaNavigation");
                });

            modelBuilder.Entity("WebApplication1.Migrations.App_Baza_Okolina", b =>
                {
                    b.HasOne("WebApplication1.Migrations.App", "IDAppNavigation")
                        .WithMany()
                        .HasForeignKey("IDApp")
                        .HasConstraintName("FK__App_Baza___IDApp__5FB337D6");

                    b.HasOne("WebApplication1.Migrations.Baza", "IDBazaNavigation")
                        .WithMany()
                        .HasForeignKey("IDBaza")
                        .HasConstraintName("FK__App_Baza___IDBaz__60A75C0F");

                    b.HasOne("WebApplication1.Migrations.Okolina", "IDOKLNavigation")
                        .WithMany()
                        .HasForeignKey("IDOKL")
                        .HasConstraintName("FK__App_Baza___IDOKL__619B8048");

                    b.Navigation("IDAppNavigation");

                    b.Navigation("IDBazaNavigation");

                    b.Navigation("IDOKLNavigation");
                });
#pragma warning restore 612, 618
        }
    }
}
